project_id = "jhnnmmwgdrquwjytvvwu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-payment]
    verify_jwt = false
  [functions.create-payment]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.image-proxy]
    verify_jwt = false
  [functions.mcp-server]
    verify_jwt = false
  [functions.rd]
    verify_jwt = false
  [functions.wechat-reader]
    verify_jwt = false
  [functions.articles-api]
    verify_jwt = false
  [functions.admin-stats]
    verify_jwt = false
  [functions.api-keys]
    verify_jwt = false
