// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/read.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseService() {
  const key = configuredEnv(["SUPABASE_SERVICE_ROLE_KEY"]);
  if (!key) throw new Error("SUPABASE_SERVICE_ROLE_KEY is required");
  return createClient(supabaseProjectUrl(), key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/format.ts
var FOOTER = "_Powered by [ReadGZH](https://readgzh.site) \xB7 [\u5F00\u53D1\u8005\u6587\u6863](https://readgzh.site/docs)_";
function bareSlug(slug) {
  return String(slug ?? "").replace(/^s\//, "");
}
function articleMarkdown(article, note) {
  const parts = [`# ${article.title ?? "Untitled"}`, ""];
  if (article.author) parts.push(`**Author:** ${article.author}`);
  if (article.publish_time) parts.push(`**Published:** ${article.publish_time}`);
  if (article.source_url) parts.push(`**Original URL:** ${article.source_url}`);
  if (article.slug) parts.push(`**Readable link:** https://readgzh.site/${article.slug}`);
  if (note) parts.push(`**Note:** ${note}`);
  parts.push("", "---", "", article.content ?? "", "", "---", FOOTER);
  return parts.join("\n");
}
function listMarkdown(heading, rows) {
  const lines = [`# ${heading} (${rows.length})`, ""];
  rows.forEach((row, index) => {
    lines.push(`## ${index + 1}. ${row.title ?? "Untitled"}`);
    if (row.author) lines.push(`- **Author:** ${row.author}`);
    if (row.publish_time) lines.push(`- **Published:** ${row.publish_time}`);
    if (row.slug) {
      lines.push(`- **Link:** https://readgzh.site/${row.slug}`);
      lines.push(`- **Read it:** call \`readgzh_get\` with slug "${bareSlug(row.slug)}"`);
    }
    lines.push("");
  });
  lines.push(FOOTER);
  return lines.join("\n");
}
function text(value) {
  return { content: [{ type: "text", text: value }] };
}
function errorText(value) {
  return { content: [{ type: "text", text: value }], isError: true };
}

// src/lib/mcp/tools/read.ts
var ARTICLE_FIELDS = "title, author, content, publish_time, source_url, slug";
var CREDIT_COST = 3;
function normalizeUrl(raw) {
  try {
    const url = new URL(raw.trim());
    if (!/(^|\.)weixin\.qq\.com$/.test(url.hostname)) return null;
    return url.toString();
  } catch {
    return null;
  }
}
var read_default = defineTool({
  name: "readgzh_read",
  title: "Read WeChat article",
  description: "Read the full text of a WeChat Official Account (\u5FAE\u4FE1\u516C\u4F17\u53F7) article from its mp.weixin.qq.com URL. Returns title, author, publish time and clean Markdown content. Cached articles are free; a fresh extraction costs 3 credits from the signed-in user's ReadGZH balance.",
  inputSchema: {
    url: z.string().describe("Full WeChat article URL, e.g. https://mp.weixin.qq.com/s/xxxx")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ url }, ctx) => {
    if (!ctx.isAuthenticated()) return errorText("Not authenticated. Reconnect the ReadGZH MCP server and sign in.");
    const target = normalizeUrl(url);
    if (!target) return errorText("Only mp.weixin.qq.com article links are supported.");
    const anon = supabaseAnon();
    const { data: cached } = await anon.from("articles").select(ARTICLE_FIELDS).eq("source_url", target).maybeSingle();
    if (cached) return text(articleMarkdown(cached, "cached \u2014 0 credits"));
    const { data: keys, error: keyError } = await supabaseForUser(ctx).from("api_keys").select("key_hash, created_at").eq("is_active", true).order("created_at", { ascending: true }).limit(1);
    if (keyError) return errorText(`Could not load your ReadGZH account: ${keyError.message}`);
    if (!keys || keys.length === 0) {
      return errorText(
        "No active ReadGZH API key on this account. Create one (free, 30 credits/day) at https://readgzh.site/dashboard, then retry."
      );
    }
    const service = supabaseService();
    const { data: quota, error: quotaError } = await service.rpc("validate_api_key", {
      p_key_hash: keys[0].key_hash,
      p_credit_cost: CREDIT_COST
    });
    if (quotaError) return errorText(`Credit check failed: ${quotaError.message}`);
    const result = quota;
    if (!result?.valid) return errorText("Your ReadGZH API key is not valid or has been disabled.");
    if (!result.allowed) {
      return errorText(
        "Out of credits for today. Claim your daily free credits or upgrade at https://readgzh.site/pricing."
      );
    }
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 55e3);
    let scrape;
    try {
      const response = await fetch(`${supabaseProjectUrl()}/functions/v1/wechat-reader`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${globalThis.Deno?.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""}`
        },
        body: JSON.stringify({ url: target }),
        signal: controller.signal
      });
      scrape = await response.json();
    } catch (err) {
      return errorText(
        `Extraction timed out or failed: ${err instanceof Error ? err.message : "unknown error"}. Please retry.`
      );
    } finally {
      clearTimeout(timeout);
    }
    if (!scrape?.success || !scrape.articleId) {
      return errorText(`Failed to read article: ${scrape?.error ?? "unknown error"}${scrape?.hint ? `
${scrape.hint}` : ""}`);
    }
    const { data: article, error } = await anon.from("articles").select(ARTICLE_FIELDS).eq("id", scrape.articleId).maybeSingle();
    if (error || !article) return errorText("Article was extracted but could not be loaded back. Please retry.");
    const remaining = typeof result.remaining === "number" ? `${CREDIT_COST} credits used, ${result.remaining} remaining` : void 0;
    return text(articleMarkdown(article, remaining));
  }
});

// src/lib/mcp/tools/search.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var search_default = defineTool2({
  name: "readgzh_search",
  title: "Search cached articles",
  description: "Search WeChat articles already cached by ReadGZH, by keyword in title or content (Chinese or English). Returns matching titles and slugs; read one with readgzh_get.",
  inputSchema: {
    query: z2.string().describe("Search keyword"),
    limit: z2.number().optional().describe("Maximum results, default 5, capped at 20")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const keyword = String(query ?? "").trim().slice(0, 100);
    if (!keyword) return errorText("Missing search keyword.");
    const max = Math.min(Math.max(Number(limit) || 5, 1), 20);
    const { data, error } = await supabaseAnon().rpc("search_public_articles", {
      p_query: keyword,
      p_limit: max
    });
    if (error) return errorText(`Search failed: ${error.message}`);
    const rows = data?.articles ?? [];
    if (rows.length === 0) return text(`No cached articles match "${keyword}".`);
    return text(listMarkdown(`Search results for "${keyword}"`, rows));
  }
});

// src/lib/mcp/tools/list-recent.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var list_recent_default = defineTool3({
  name: "readgzh_list",
  title: "List recent cached articles",
  description: "List the most recently cached WeChat articles on ReadGZH, newest first. Useful for browsing.",
  inputSchema: {
    limit: z3.number().optional().describe("Number of articles, default 10, capped at 50")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const max = Math.min(Math.max(Number(limit) || 10, 1), 50);
    const { data, error } = await supabaseAnon().from("articles").select("title, author, publish_time, slug").order("created_at", { ascending: false }).limit(max);
    if (error) return errorText(`Could not list articles: ${error.message}`);
    if (!data || data.length === 0) return text("No cached articles found.");
    return text(listMarkdown("Recently cached articles", data));
  }
});

// src/lib/mcp/tools/list-by-account.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var list_by_account_default = defineTool4({
  name: "readgzh_list_by_account",
  title: "List cached articles by account",
  description: "List cached WeChat articles from one Official Account (\u516C\u4F17\u53F7), newest first. Only covers articles already cached by ReadGZH \u2014 WeChat has no public archive API, so the result is never exhaustive; say so when presenting it.",
  inputSchema: {
    account: z4.string().describe("Official Account name (author); partial match supported"),
    limit: z4.number().optional().describe("Number of articles, default 10, capped at 50")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ account, limit }) => {
    const name = String(account ?? "").trim().slice(0, 100).replace(/[%_,]/g, "");
    if (!name) return errorText("Missing account name.");
    const max = Math.min(Math.max(Number(limit) || 10, 1), 50);
    const { data, error } = await supabaseAnon().from("articles").select("title, author, publish_time, slug").ilike("author", `%${name}%`).order("publish_time", { ascending: false, nullsFirst: false }).limit(max);
    if (error) return errorText(`Could not list articles: ${error.message}`);
    if (!data || data.length === 0) {
      return text(
        `No cached articles found for "${account}". ReadGZH only indexes articles that were read at least once through the service.`
      );
    }
    return text(
      `${listMarkdown(`Cached articles from "${account}"`, data)}

_Cached articles only \u2014 not the account's full archive._`
    );
  }
});

// src/lib/mcp/tools/get.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z5 } from "npm:zod@^3.25.76";
var CHUNK = 4e4;
var get_default = defineTool5({
  name: "readgzh_get",
  title: "Get cached article by slug",
  description: "Read a cached WeChat article by its ReadGZH slug. Long articles are chunked at ~40,000 characters; pass part to page through them. Always free \u2014 no credits.",
  inputSchema: {
    slug: z5.string().describe("Article slug, e.g. the value after /s/ in a ReadGZH link"),
    part: z5.number().optional().describe("Chunk number starting at 1 for long articles")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, part }) => {
    const raw = String(slug ?? "").trim();
    if (!raw) return errorText("Missing slug.");
    const bare = raw.replace(/^s\//, "");
    const anon = supabaseAnon();
    const { data, error } = await anon.from("articles").select("title, author, content, publish_time, source_url, slug").or(`slug.eq.${bare},slug.eq.s/${bare}`).limit(1).maybeSingle();
    if (error) return errorText(`Lookup failed: ${error.message}`);
    if (!data) return errorText(`No cached article with slug "${bare}". Try readgzh_search first.`);
    const article = data;
    const content = article.content ?? "";
    const total = Math.max(1, Math.ceil(content.length / CHUNK));
    const index = Math.min(Math.max(Number(part) || 1, 1), total);
    if (total === 1) return text(articleMarkdown(article));
    const chunk = content.slice((index - 1) * CHUNK, index * CHUNK);
    const note = `part ${index} of ${total}${index < total ? ` \u2014 call readgzh_get again with part: ${index + 1}` : ""}`;
    return text(articleMarkdown({ ...article, content: chunk }, note));
  }
});

// src/lib/mcp/index.ts
var projectRef = "jhnnmmwgdrquwjytvvwu";
var mcp_default = defineMcp({
  name: "readgzh",
  title: "ReadGZH",
  version: "1.0.0",
  instructions: "ReadGZH reads WeChat Official Account (\u5FAE\u4FE1\u516C\u4F17\u53F7) articles that ordinary web fetches cannot open. Use readgzh_read for an mp.weixin.qq.com link, readgzh_search / readgzh_list / readgzh_list_by_account to browse articles already cached by ReadGZH, and readgzh_get to re-read a cached article by slug (free, chunked for long articles). Cached reads cost nothing; a fresh extraction costs 3 credits from the signed-in user's ReadGZH balance. Cache listings are never a complete archive of an account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [read_default, search_default, list_recent_default, list_by_account_default, get_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
